name: hyper_rustls

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build example hyper_rustls
      run: cargo build -F "rustls_ring,use_tokio" --example hyper_rustls
