name: test_tokio_flow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test use_rustls and use_tokio
      run: cargo test --features "use_rustls,use_tokio" --verbose
