name: test_async_std_and_rustls_aws_lc_rs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test rustls_aws_lc_rs and use_async_std
      run: cargo test -F "rustls_aws_lc_rs,use_async_std"
