name: test_tokio_and_rustls_ring

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test rustls_ring and use_tokio
      run: cargo test -F "rustls_ring,use_tokio"
